use_frameworks!

platform :ios, '8.0'

target 'GameFoxOptLibs_Example' do
  pod 'GameFoxOptLibs', :path => '../'

  target 'GameFoxOptLibs_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
